<?php
/**
 * TL_ROOT/system/modules/addresses/languages/nl/tl_address.php 
 * 
 * Contao extension: addresses 0.0.2 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : LGPL 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_address']['street_2']['0'] = "Straat 2";
$GLOBALS['TL_LANG']['tl_address']['street_2']['1'] = "Voeg meer straatinformatie in, indien van toepassing.";
$GLOBALS['TL_LANG']['tl_address']['street_3']['0'] = "Street 3";
$GLOBALS['TL_LANG']['tl_address']['street_3']['1'] = "Voeg meer straatinformatie in, indien van toepassing.";
$GLOBALS['TL_LANG']['tl_address']['secondEmail']['0'] = "Tweede e-mailadres";
$GLOBALS['TL_LANG']['tl_address']['secondEmail']['1'] = "Voer een tweede e-mailadres in.";
$GLOBALS['TL_LANG']['tl_address']['isBillingAddress']['0'] = "Factuur adres";
$GLOBALS['TL_LANG']['tl_address']['isBillingAddress']['1'] = "Klik hier als dit adres het factuuradres is.";
$GLOBALS['TL_LANG']['tl_address']['isPrivateAddress']['0'] = "Prive adres";
$GLOBALS['TL_LANG']['tl_address']['isPrivateAddress']['1'] = "Klik hier als dit een prive adres is.";
$GLOBALS['TL_LANG']['tl_address']['isDefaultAddress']['0'] = "Standaard adres";
$GLOBALS['TL_LANG']['tl_address']['isDefaultAddress']['1'] = "Klik hier als dit het standaardadres van dit lid is. Alle informatie wordt gekopierd naar de ledeninfo module.";
$GLOBALS['TL_LANG']['tl_address']['personal_legend'] = "Persoonlijke informatie";
$GLOBALS['TL_LANG']['tl_address']['address_legend'] = "Adres informatie";
$GLOBALS['TL_LANG']['tl_address']['contact_legend'] = "Contactinformatie";
$GLOBALS['TL_LANG']['tl_address']['additional_legend'] = "Aanvullende informatie";
$GLOBALS['TL_LANG']['tl_address']['business_address'] = 'Zakenadres';
$GLOBALS['TL_LANG']['tl_address']['new']['0'] = "Nieuw adres";
$GLOBALS['TL_LANG']['tl_address']['new']['1'] = "Maak een nieuw adres aan";
$GLOBALS['TL_LANG']['tl_address']['show']['0'] = "Toon adresdetails";
$GLOBALS['TL_LANG']['tl_address']['show']['1'] = "Toon details van adres ID %s.";
$GLOBALS['TL_LANG']['tl_address']['edit']['0'] = "Adres bewerken";
$GLOBALS['TL_LANG']['tl_address']['edit']['1'] = "Wijzig adres ID %s";
$GLOBALS['TL_LANG']['tl_address']['copy']['0'] = "Adres kopieren";
$GLOBALS['TL_LANG']['tl_address']['copy']['1'] = "Dupliceer adres ID %s";
$GLOBALS['TL_LANG']['tl_address']['delete']['0'] = "Adres verwijderen";
$GLOBALS['TL_LANG']['tl_address']['delete']['1'] = "Verwijder adres ID %s";
 
