<?php
/**
 * TL_ROOT/system/modules/addresses/languages/nl/tl_member.php 
 * 
 * Contao extension: addresses 0.0.2 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2011 Liplex Webprogrammierung und -design Christian Kolb 
 * License   : LGPL 
 * Author    : Christian Kolb (Liplex), www.liplex.de 
 * Translator: Paul Kegel (artified), www.artified.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['addresses']['0'] = "Adressen";
$GLOBALS['TL_LANG']['tl_member']['addresses']['1'] = "Beheer de adressen van lid ID %s";
